Feature loby page
FredrikHj/projekt_-AgilScrum pull request #36
Opened 2020-01-02 15:57 UTC by FredrikHj

#18 #28 #17 #19  

Fyra kort inkluderat men vet att ju färre desto bättre :)

2020-01-02 16:52 UTC, GitRall requested changes
Finns två Components folders, Den som börjar med stor bokstav ser ut att vara överflödig.

2020-01-02 16:52 UTC, GitRall commented on src/components/pages/startPage.js
> +import {
Router används inte i denna komponenten.

2020-01-02 16:52 UTC, GitRall commented on src/components/pages/lobbyPage.js
> +import {
Router används inte i denna komponenten.

2020-01-02 16:52 UTC, GitRall commented on src/logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 841.9 595.3">
Denna filen kan tas bort

2020-01-05 16:34 UTC, GitRall submitted a review, later dismissed

2020-01-05 20:38 UTC, GitRall approved these changes

2020-01-07 07:44 UTC, silfverstrom approved these changes
Ser bra ut, men den här PRn saknas tester. Kan ni lägga till en issue som beskriver att testerna ska skrivas till Lobbyn?

2020-01-08 09:16 UTC, merged

2020-01-09 13:24 UTC, FredrikHj commented
Test = Done :)