added polling to game
FredrikHj/projekt_-AgilScrum pull request #44
Opened 2020-01-03 16:13 UTC by GitRall

#40 Added polling in game

2020-01-05 12:13 UTC, osynkad approved these changes
👍

2020-01-07 07:35 UTC, silfverstrom requested changes
Bra jobbat, hittade lite AJAX-anrop som inte fångas - kan vara bra att lägga till exception handling.

2020-01-07 07:35 UTC, silfverstrom commented on src/components/pages/gamePage.js
> +    axios.get(`http://emil.nilsson.link/api/game/${paramId}`)
Lägga URI:n i en config?

2020-01-07 07:35 UTC, silfverstrom commented on src/components/pages/gamePage.js
> +        .then((res) => {
Vi fångar inte errors här, kan vi lägga till en catch och validera res?

2020-01-07 07:35 UTC, silfverstrom commented on src/components/pages/gamePage.js
> +    axios.post(`http://emil.nilsson.link/api/game/${paramId}/move`, payload)
Fångar inte errors här heller.

2020-01-07 10:10 UTC, silfverstrom approved these changes
gj!

2020-01-07 12:15 UTC, merged