Feature backend
FredrikHj/projekt_-AgilScrum pull request #49
Opened 2020-01-07 16:33 UTC by osynkad

closes #15 & #47

2020-01-09 09:28 UTC, GitRall approved these changes
Ser fint ut!

2020-01-10 07:38 UTC, silfverstrom approved these changes
Bra testat i komponenten! 
Hittade en liten issue

2020-01-10 07:38 UTC, silfverstrom commented on server/server.js
> +  gamesCopy = games.filter((game) => {
Saknas variable deklaration här. const/let

2020-01-10 07:38 UTC, silfverstrom requested changes
Hittade en issue där det saknas variabel deklaration

2020-01-10 08:16 UTC, osynkad commented on server/server.js
> +  gamesCopy = games.filter((game) => {
fixat!

2020-01-13 09:15 UTC, silfverstrom approved these changes
Bra! Ursäkta fördröjningen

2020-01-13 09:15 UTC, merged